version: "3.9"

services:
  api:
    container_name: papper-ocr-service
    build:
      context: .
      dockerfile: docker/dev.Dockerfile
    ports:
      - "${SERVICE_PORT}:8000"
    volumes:
      - ./${WEIGHTS_FOLDER}:/usr/data/app/${WEIGHTS_FOLDER}
      - ./.:/usr/data/app
    restart: unless-stopped
    command: >
      sh -c "uvicorn src.main:app --host 0.0.0.0 --port 8000 --log-config src/uvicorn-logging-config. --reload"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: [ '0' ]
              capabilities: [ gpu ]